# デフォルトのペイン分割を設定
set-hook -g after-new-session 'split-window -h -p 40'

# viモードでコピー操作
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
